### ISSUE TITLE
Change MathJaxR font family in Shiny app

### ISSUE THREAD

**Issue by MinhChauVanNguyen** [vnijs/MathJaxR#2]
Hi @vnijs,

I am just wondering if it's possible to change the font family of MathJaxR equation, ideally I want the font family to be **monospace**. I have tried changing this in css but it didn't seem to work so I figure I might have got the wrong class specified. 

**styles.css**
```
div.MathJax_Display{
   text-align:center !important;
   font-family:monospace !important;
}
.MathJax body{font-family:monospace;}
```

**SERVER.R**
```
observeEvent(input$calculation,{
  createAlert(session, anchorId = "percentage", alertId = "Alert4", title = "<center><font size='20px'>IMPORTANT</font></center>",
              content = HTML("<div class=alert alert-info, role=alert style='color:black;font-family:monospace;'>
                      $$\\textrm{one} = \\frac{53.2 \\times \\textrm{two}}{\\textrm{three}}$$<script>MathJax.Hub.Queue(['Typeset', MathJax.Hub]);</script>"), 
            append = FALSE, style = "info")
})
```

**OUTPUT**
<img width="261" alt="Screen Shot 2020-07-09 at 10 35 43 AM" src="https://user-images.githubusercontent.com/61895317/86977171-26691280-c1d0-11ea-9b65-8d1212fb08f6.png">

Many thanks.

**Comment by vnijs** [comment]
@MinhChauVanNguyen This is just a convenience repo I created for myself. I don't have anything to do with MathJax so unfortunately, can't help you. If you have a question about using MathJax with Rmarkdown or Shiny, I recommend you post to https://community.rstudio.com/
